var ALIASES = {};
ALIASES["foolsgold"] = {};
ALIASES["mruby"] = {};
ALIASES["mruby_bin"] = {};
ALIASES["mruby_gems"] = {};
ALIASES["mruby_sys"] = {};
ALIASES["mruby_vfs"] = {};
ALIASES["nemesis"] = {};
ALIASES["rirb"] = {};
