(function() {var implementors = {};
implementors["cactusref"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"cactusref/trait.Reachable.html\" title=\"trait cactusref::Reachable\">Reachable</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"cactusref/struct.CactusRef.html\" title=\"struct cactusref::CactusRef\">CactusRef</a>&lt;T&gt;",synthetic:false,types:["cactusref::CactusRef"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"cactusref/trait.Reachable.html\" title=\"trait cactusref::Reachable\">Reachable</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"cactusref/struct.CactusWeakRef.html\" title=\"struct cactusref::CactusWeakRef\">CactusWeakRef</a>&lt;T&gt;",synthetic:false,types:["cactusref::CactusWeakRef"]},];
implementors["mruby"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"mruby/gc/struct.ArenaIndex.html\" title=\"struct mruby::gc::ArenaIndex\">ArenaIndex</a>",synthetic:false,types:["mruby::gc::ArenaIndex"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"mruby/state/struct.State.html\" title=\"struct mruby::state::State\">State</a>",synthetic:false,types:["mruby::state::State"]},];
implementors["mruby_bin"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"mruby_bin/parser/struct.Parser.html\" title=\"struct mruby_bin::parser::Parser\">Parser</a>",synthetic:false,types:["mruby_bin::parser::Parser"]},];
implementors["mruby_vfs"] = [{text:"impl&lt;Metadata:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"mruby_vfs/struct.FakeTempDir.html\" title=\"struct mruby_vfs::FakeTempDir\">FakeTempDir</a>&lt;Metadata&gt;",synthetic:false,types:["mruby_vfs::fake::tempdir::FakeTempDir"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
