(function() {var implementors = {};
implementors["mruby"] = [{text:"impl&lt;To, From&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"mruby/convert/struct.Error.html\" title=\"struct mruby::convert::Error\">Error</a>&lt;To, From&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;From: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;To: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a>,&nbsp;</span>",synthetic:false,types:["mruby::convert::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"mruby/enum.MrbError.html\" title=\"enum mruby::MrbError\">MrbError</a>",synthetic:false,types:["mruby::MrbError"]},];
implementors["nemesis"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"nemesis/handler/enum.Error.html\" title=\"enum nemesis::handler::Error\">Error</a>",synthetic:false,types:["nemesis::handler::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"nemesis/request/enum.Error.html\" title=\"enum nemesis::request::Error\">Error</a>",synthetic:false,types:["nemesis::request::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"nemesis/response/enum.Error.html\" title=\"enum nemesis::response::Error\">Error</a>",synthetic:false,types:["nemesis::response::Error"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
